### ISSUE TITLE
activerecord-pg_enum

### ISSUE THREAD

**Issue by pirj** [bibendi/activerecord-postgres_enum#15]
Hey!

There's a very similar project [`activerecord-pg_enum`](https://github.com/alassek/activerecord-pg_enum), started roughly at the same time, and with comparable features. It also features a helper to specify enums in models.

Would you consider merging efforts?

/cc @alassek

**Comment by bibendi** [comment]
Hi.

I don't plan to spend any efforts on this gem in the near future, because of the merging of two different codebases don't make sense for me. I more like the idea to propose this feature to the Rails. Probably I'll rich that goal by the end of the year.

**Comment by pirj** [comment]
Awesome, good to know. The plan sounds realistic with MySQL enum types and SQLite3's `CHECK` constraint.
Eagerly looking forward to seeing this landing in Rails 👍
