### ISSUE TITLE
Add drop_enum(:my_enum_type, force: :cascade, if_exists: true)

### ISSUE THREAD

**Issue by shaicoleman** [bibendi/activerecord-postgres_enum#24]
Hi, would be useful to support to support `:if_not_exists` for `create_enum`, e.g.:
```
create_enum(:my_enum, %w(opt1 opt2), :if_not_exists: true)
```

And `force: :cascade` and `if_exists: true` for `drop_enum`

Thanks

**Comment by bibendi** [comment]
Duplicates #23

**Comment by hosembafer** [comment]
@bibendi seems it's not duplicate of #23, because it's about create_enum and drop_enum, not about enum values. I opened PR for this issue, take a look #27
