### ISSUE TITLE
Guidance for existing pg enums

### ISSUE THREAD

**Issue by darkporpoise** [bibendi/activerecord-postgres_enum#28]
Thanks for the gem, it looks like it does exactly what I'm after!

I have previously been creating enums using SQL (example below) but it renders my schema.rb inoperable.

Could you give me some pointers for implementing your gem into my existing project?

Thanks!

<details><summary>SQL</summary>

```ruby
class AddStatusToAreas < ActiveRecord::Migration[5.2]
  def change
    reversible do |dir|
      dir.up do
        execute <<-SQL
          CREATE TYPE area_status AS ENUM ('active', 'archived');
        SQL
      end
      dir.down do
        execute <<-SQL
          DROP TYPE area_status;
        SQL
      end
    end

    add_column :areas, :status, :area_status, default: 'active', null: false
    add_index :areas, :status
  end
end
```

</details>

**Comment by bibendi** [comment]
Hi!

I have no specific instructions to make this gem into an existing project. It should just work.
What is the particular problem do you have?

**Comment by darkporpoise** [comment]
I'm sorry, I haven't tried just adding the gem and regenerating the schema!

I had assumed the gem would need to know the details of the pre-existing enums in order to include them in schema.rb. I'll have a play and get back to you.
