### ISSUE TITLE
Rails 7 create_enum generates array of arrays in schema.rb

### ISSUE THREAD

**Issue by dpaluy** [bibendi/activerecord-postgres_enum#55]
After migrating from Rails 6.1 to Rails 7 and updating this gem to 2.0.0
the schema.rb isn't generated correctly.

My migration is:

```ruby
class AddMood < ActiveRecord::Migration[7.0]
  def change
    create_enum :mood, %w(happy great been_better)
  end
end
```

The `schema.rb` result is:

```ruby
ActiveRecord::Schema.define(version: 2021_12_24_061446) do
  create_enum :mood, [["happy", "great", "been_better"]]
end
```

This **double array** fails when running: `rake db:schema:load`

**Expected behavior**

```ruby
ActiveRecord::Schema.define(version: 2021_12_24_061446) do
  create_enum :mood, ["happy", "great", "been_better"]
end
```

**Context (please complete the following information):**
 - OS: MacOs 12.1
 - Gem Version: 2.0.0

**Comment by bibendi** [comment]
Thank you for the reporting!
Can you try `fix/rails-7-schema-dumper` branch?

**Comment by dpaluy** [comment]
@bibendi  Your fix works correctly. Thank you for the prompt fix

**Comment by bibendi** [comment]
Cool. I'll release the gem now.
